SMP GIRQ locking fix
ThomasSchnuerer/mdis_drivers_bbis_chameleon_com pull request #1
Opened 2021-07-12 08:41 UTC by JFriesz

This merge request fixes a locking problem with GIRQ and Chameleon BBIS which occured under VxWorks.
As discussed, this should be also applicable for linux.

2021-07-12 11:23 UTC, dpfeuffer requested changes

2021-07-12 11:23 UTC, dpfeuffer commented on DRIVER/COM/bb_chameleon.c
> +      int i = 0;
Better move variable declarations to the beginning of the function to be ANSI C conform (we have to support Linux kernel 3.16 and I'm unsure if older GCC compiler supports C99).

2021-07-13 07:02 UTC, JFriesz commented on DRIVER/COM/bb_chameleon.c
> +      int i = 0;
Moved them to the beginning.

2021-07-13 07:13 UTC, dpfeuffer approved these changes
No compilation tests nor functional test made under Linux.

2021-07-13 07:15 UTC, merged